### ISSUE TITLE
Visualizations updates are not stable and leaving visualizations blank

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6561]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

During building up use-cases and demos we observed the decrease in visualizations stability. That include:
- [ ] visualization is blanked after finishing editing a node
- [ ] blank visualizations after nodes collapsing,
- [ ] blank visualization on an existing node with viz opened while uploading the new file,
- [ ] no update for the full screen visualization if it was opened before IDE got the data - it is never updated and needs reopening,
- [ ] clicking on the drop-down to select a visualization is vanishing the visualization. 
### Expected behaviour

Visualizations should be updated with the data as soon as data are available.

### Enso Version

nightly 04.05

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by wdanilo** [comment]
Question – we had so many issues about it already. Do we have any insights why it is happening? Why can't we just fix the GUI - backend communication once for all and prevent such issues from happening ever again? Basically, my question here is - what is exactly the cause of this / similar to this issues? Is it some kind of race condition / bugs in communication / something else? 

CC @4e6 as you'd probably know the answer to these questions :)

**Comment by 4e6** [comment]
The IDE has basically two feedback channels from the engine - expression and visualization updates. And when anything goes wrong, the user can only observe it by seeing the wrong updates. Here are the last issues related to visualizations

- #6493
  The issue with the dropdowns (which are utilizing the visualization updates channel) was fixed in the compiler pass
- #6423
  The issue with table visualizations blanking was caused by the library function catching the interruption exception
- #6354 
  Some visualizations that were not showing up after the project startup was caused by the job engine

All causes were completely different

**Comment by 4e6** [comment]
The issue I can reproduce on the current develop seems like on the IDE side 


https://user-images.githubusercontent.com/357683/236459699-e593c78a-2f30-4455-8dd7-5e87d98d628b.mp4

**Comment by sylwiabr** [comment]
@4e6 thank you for checking. Package from 29.04 does not have those issues, package from 02.05 does. This means the regression was caused by #6458 or #6461. As #6461 was just touching debug scenes not application probably the issue was introduced with #6458 - @kazcw can you have a look at this?

**Comment by kazcw** [comment]
Looking into it.

**Comment by kazcw** [comment]
If I revert that commit (and related commit #6569), I can still reproduce the bug.

**Comment by 4e6** [comment]
May be related #6526

**Comment by kazcw** [comment]
The bug still occurs on `develop` after reverting #6458 (and dependent PR #6569).

I suspect it's older than 02.05. The bug is sensitive to the exact testing procedure: Immediately after creating a new node the bug is present when editing the node, but if I open a project and edit an already existing node the bug isn't triggered. (This made attempts to narrow down the cause "interesting").

**Comment by MichaelMauderer** [comment]
Note that I can repro https://github.com/enso-org/enso/issues/6561#issuecomment-1536205322 (and have a PR with a fix), but I cannot repro 
> 
    blank visualizations after nodes collapsing,
    blank visualization on an existing node with viz opened while uploading the new file,
    no update for the full screen visualization if it was opened before IDE got the data - it is never updated and needs reopening.

I think we should open separate issues for these, as they appear unrelated.

**Comment by MichaelMauderer** [comment]
@sylwiabr Could you double-check these issues
* blank visualizations after nodes collapsing,
* blank visualization on an existing node with viz opened while uploading the new file,
* no update for the full screen visualization if it was opened before IDE got the data - it is never updated and needs reopening.

are still happening on your end? I cannot repro them. If they still appear, I will create separate issues.

**Comment by sylwiabr** [comment]
@MichaelMauderer 
- blank visualizations after nodes collapsing - still there,
- no update for the full screen visualization if it was opened before IDE got the data - it is never updated and needs reopening - still there,
- blank visualization on an existing node with viz opened while uploading the new file - doesn't appear but will check again,
- new one: clicking on visualization chooser vanish the visualization 

Let's do it as a single ticket bu we can fix them in separate PRs.

**Comment by sylwiabr** [comment]
I have updated the description so we can mark the thing that were fixed.

**Comment by MichaelMauderer** [comment]
@sylwiabr I'll try to repro on another machine/OS, but any additional hints and videos would be very useful.

**Comment by sylwiabr** [comment]
Video for collapsing nodes:

https://github.com/enso-org/enso/assets/12892578/b2d0be37-c481-4590-91f6-bf343d06e389

There are errors regarding geomap vis but they are not relevant to this issue.

**Comment by sylwiabr** [comment]
no update for the full screen visualization if it was opened before IDE got the data - it is never updated and needs reopening - video:

https://github.com/enso-org/enso/assets/12892578/1d1591e1-235c-4211-b7fe-a83cb807c6d3

**Comment by sylwiabr** [comment]
clicking on the drop-down to select a visualization is vanishing the visualization - video:

https://github.com/enso-org/enso/assets/12892578/748b6afe-3b80-4e60-80b9-b5e69e146f2b
