### ISSUE TITLE
Send info about function values to the IDE

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#6957]
Based on [language server API discussion](https://github.com/orgs/enso-org/discussions/6762), analysis while working on [bug 6903](https://github.com/enso-org/enso/issues/6903#issuecomment-1572850032) and [request for changes in #6939](https://github.com/enso-org/enso/pull/6939#pullrequestreview-1464273966) I am proposing following path forward:

[ProgramExecutionSupport.scala](https://github.com/enso-org/enso/blob/03371803849aa44d267856f3c6b828f97e602e7a/engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala#L386) needs to do following when composing `sendExpressionUpdate`:
- when the `value.getType` is `Standard.Builtins.Main.Function`
- accompany the information with a `MethodPointer` to the function definition
- use `(value.value : runtime.Function).getSchema()` to obtain `hasPreApplied` array and send it to the IDE somehow

This fixes problems with _partially applied constructors and functions_ and lets the IDE know what arguments have already been applied sooner when `Function` value arrives. The IDE however needs to process this additional information somehow.

**Comment by 4e6** [comment]
The #6939 is already doing what you are proposing:

https://github.com/enso-org/enso/blob/c9999b1149e8cf87784ac886bcae340d93c5e713/engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java#L328-L330

- (line 328) When the value is a function 
- (line 329) Accompany the information with a MethodPointer (it is represented as a `FunctionCallInfo`)
- (line 330) use `function.getSchema()` to obtain `hasPreApplied` array. The `FunctionCallInfo` constructor does exactly this:
https://github.com/enso-org/enso/blob/c9999b1149e8cf87784ac886bcae340d93c5e713/engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionService.java#L318-L328

**Comment by JaroslavTulach** [comment]
> The #6939 is already doing what you are proposing:

Kind of, but not exactly:
- It is great to see we can convert a `result instanceof Function` into correct [data that the IDE needs](https://github.com/orgs/enso-org/discussions/6762#discussioncomment-6090661)
- I still see ` if (constructorCalls.contains(nodeId)` in #6939 and that is superfluous

Each `result instanceof Function` shall be sent to the IDE as `FunctionCallInfo` and it doesn't matter where it is originating from - whether it is a result of applying a constructor or calling a function. Such detailed information about the `result instanceof Function` has to be [delivered as soon as possible](https://github.com/orgs/enso-org/discussions/6762#discussioncomment-6090661) without forcing the IDE to perform any textual edits. Particularly interesting test case is:
```
text1 = "  hello ! "
operator4 = Text.trim
operator5 = operator4 where=Location.Start
operator7 = operator5 text1
```



![Partially applied Text.trim function](https://github.com/enso-org/enso/assets/26887752/b4ad1bd0-cb77-40c5-8e44-db90b81dd59b)


Will the code currently proposed in #6939 deliver `FunctionCallInfo` information about `operator5` to the IDE? Will the IDE **not display** `where` attribute when invoking `operator5`?

**Comment by 4e6** [comment]
This issue was addressed in #6867 by sending the list of not applied arguments together with the method pointer. #6939 is a follow-up to that PR and is only supposed to send the correct arguments in case of constructor calls.

**Comment by JaroslavTulach** [comment]
One more example that illustrates the problem with _function value_ vs. the last _executed function_:

![Pair.second](https://github.com/enso-org/enso/assets/26887752/53a76bfa-bc1a-4003-96b6-9a748e96b4cd)

The program _"hides"_ the `Text.trim` function inside of `Pair` and then obtains it as `Pair.second` later. It is still the same `Text.trim` function - e.g. the IDE shall offer list of not yet applied arguments. It should offer `where` and `what` in the last node, in my opinion.

**Comment by 4e6** [comment]
A follow-up to the call when we were discussing the case when the function is read from the variable

```py
main =
    x1_1 = T.func1
    x1_2 = x1_1
    x1 = x1_2 1 2
    x1

type T
    A

    func1 x y = x + y
```

`x1_1` expression (`ReadLocalVariableNode`) is not wrapped in the `FunctionCallInstrumentationNodeWrapper` (only function applications are) and does not have the method pointer associated with it.

Tracking PR with a test case #6986

**Comment by JaroslavTulach** [comment]
This case shall continue to work the same way it works now:
![obrazek](https://github.com/enso-org/enso/assets/26887752/22e8884e-47e1-40c9-b2cc-f95c7a314cb2)

**Comment by JaroslavTulach** [comment]
Think about `...` operator:
![obrazek](https://github.com/enso-org/enso/assets/26887752/e0dc4333-e1db-4d33-bed8-80c7307467a8)

**Comment by 4e6** [comment]
Summary of the discussion with @Frizi and @JaroslavTulach 

IDE needs additional information to display the placeholders for the arguments of partially applied functions. 

- When the return value is a function, the `Payload` of [`ExpressionUpdate`](https://github.com/enso-org/enso/blob/a31c6715244453d1bdd01dcf64178a0409cb5454/docs/language-server/protocol-language-server.md#expressionupdate) should provide additional `MethodCall` information (`MethodPointer` + argument infos) 
- In case of the complex expression
  ```py
    Pair.Value 1 2
  ```
   When the `Pair.Value` subexpression is annotated, it returns an `ExpressionUpdate` with a function return type and a payload containing the method call information of the returned function
