### ISSUE TITLE
Strange behavior of `Standard.Visualization.AI.build_ai_prompt` extension method.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#9518]
In https://github.com/enso-org/enso/pull/9476 I needed to remove one extension method implementation because it caused weird responses in the GUI: when GUI tried to make `executeExpression` call with `Standard.Visualization.AI.build_ai_prompt (operator31241)` expression, it got error `"Type error: expected a function, but got ````"`

Calling the method in my code also gave me the placeholder of any, even when I had attached something of Table type:
![image](https://github.com/enso-org/enso/assets/3919101/7f8d401e-7bde-4937-87c2-3a5bb0e588b4)

When doing all above actions, I already was having the reexport of AI module in Standard.Visualization Main.

**Comment by 4e6** [comment]
To summarize, there are three definitions in the `AI` module:
```py
Table.build_ai_prompt self = <impl>

Any.build_ai_prompt self = "````"

build_ai_prompt subject = subject.build_ai_prompt
```

~~The expression `Standard.Visualization.AI.build_ai_prompt table` chooses the `Any` implementation and returns ` "````" `~~. The issue is fixed when the `Any.build_ai_prompt` extension method is removed.

#### Update
The expression `Standard.Visualization.AI.build_ai_prompt` returns ` "````" ` when called without arguments

**Comment by radeusgd** [comment]
I'm wondering if this may somehow be related to #6441 - it introduced some special handling of methods defined directly on the `Any` type.

**Comment by JaroslavTulach** [comment]
As an easy to reproduce inquiry: Can we get source code of a program to run and its current/desired output? Thank you. One the program is attached, please reassign back to me.

**Comment by 4e6** [comment]
Should be fixed by #6553

**Comment by 4e6** [comment]
@JaroslavTulach the #6553 didn't fix the issue for me

## How to reproduce

Uncomment the `Any.build_ai_prompt` implementation: https://github.com/enso-org/enso/blob/a474955e282f28723b81acf433d47543bdf603bc/distribution/lib/Standard/Visualization/0.0.0-dev/src/AI.enso#L31-L33

run `Main.enso`
```py
from Standard.Base import all
from Standard.Table import all
from Standard.Database import all
from Standard.AWS import all
import Standard.Visualization


main =
    Standard.Visualization.AI.build_ai_prompt
```

### Expected

```
$ ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --no-ir-caches --no-global-cache --run ~/enso/projects/Test_Ai_Prompt/src/Main.enso
[WARN] [2024-04-03T15:48:38+01:00] [org.enso.librarymanager.local.DefaultLocalLibraryProvider] Local library search path [***/libraries] does not exist.
AI.build_ai_prompt[AI.enso:36:1-49] self=AI subject=_
```

### Actual

```
$ ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --no-ir-caches --no-global-cache --run ~/enso/projects/Test_Ai_Prompt/src/Main.enso
[WARN] [2024-04-03T15:50:11+01:00] [org.enso.librarymanager.local.DefaultLocalLibraryProvider] Local library search path [***/libraries] does not exist.
 ````
```

**Comment by JaroslavTulach** [comment]
The "problem" happens in [InvokeMethodNode](https://github.com/enso-org/enso/blame/07793f576b40043f17bba85dd93dd2e5e7296ffb/engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java#L176). 
```ruby
if (where instanceof MethodRootNode node && typeCanOverride(node, ctx)) {
      Type any = ctx.getBuiltins().any();
      Function anyFun = symbol.getScope().lookupMethodDefinition(any, symbol.getName());
      if (anyFun != null) {
        function = anyFun;
      }
```
`typeCanOverride` returns true and then the method is found on `Any` and it takes precedence over the static one. The code was introduced by @hubertp 
- #6441

Btw. Simplest solution would be to rename the static method...

**Comment by hubertp** [comment]
I'm a bit surprised it didn't resolve the function. Then it clearly wouldn't try methods on `Any`. How about lifting the method to `AI` type?

```
type AI
    build_ai_prompt prompt = ...
```
rather than having a method on a module?

**Comment by JaroslavTulach** [comment]
> I'm a bit surprised it didn't resolve the function. Then it clearly wouldn't try methods on `Any`. 

It did found the module function, but then this code decided to throw it away and use the `Any.build_ai_prompt`.

**Comment by hubertp** [comment]
> > I'm a bit surprised it didn't resolve the function. Then it clearly wouldn't try methods on `Any`.
> 
> It did found the module function, but then this code decided to throw it away and use the `Any.build_ai_prompt`.

Alright, now I recall what was it about. The trick with `type AI` won't work either, as this was all the requirement from libraries, IIRC (see https://github.com/enso-org/enso/blob/develop/test/Base_Tests/src/Semantic/Any_Spec.enso#L41).

<blockquote><img src="https://opengraph.githubassets.com/8e2122538571e91eb1a69c98e34f90c68eac6d76d386353000e06088287649f0/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/blob/develop/test/Base_Tests/src/Semantic/Any_Spec.enso">enso/test/Base_Tests/src/Semantic/Any_Spec.enso at develop · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by JaroslavTulach** [comment]
- there really is [Standard.Visualization.AI](https://github.com/enso-org/enso/blob/cc9c257e18ff2b144ee316d2c33010ae510969c5/distribution/lib/Standard/Visualization/0.0.0-dev/docs/api/AI.md)!
- can we remove it, @jdunkerley?

**Comment by JaroslavTulach** [comment]
> `typeCanOverride` returns true and then the method is found on `Any` and it takes precedence over the static one.

- the logic of static/instance method dispatch has been greatly improved by @Akirathan in
- #13961
- #13962
- thus I believe this problem has a chance to be obsolete and I will close it unless we want to remove `Standard.Visualization.AI`
